import "./globals.css";
import { Inter } from "next/font/google";
import ApolloSetting from "@/commons/setting/apollo-setting";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body className={inter.className}>
        {/* 전역 Apollo Provider */}
        <ApolloSetting>
          {children}
        </ApolloSetting>
      </body>
    </html>
  );
}
